# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /io/tensorboard, last modified Wed Apr  3 13:42:34 2019
# ------------------------------------------------

package:
    name: tensorboard
    version: 1.13.1
source:
    fn: tensorboard-1.13.1.tar.gz
    sha256: eab7cb36b32b331fdb8f9dd95335ffb8e281b93cc701e0849f73bbaddaebb988
    url: https://github.com/tensorflow/tensorboard/archive/1.13.1.tar.gz
build:
    entry_points:
        - tensorboard = tensorboard.main:run_main
    number: '0'
    string: py37hf484d3e_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_6
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - bazel 0.22.0 he6710b0_0
        - ca-certificates 2019.1.23 0
        - certifi 2019.3.9 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 he6710b0_1
        - openjdk 8.0.152 h46b5887_1
        - openssl 1.1.1b h7b6447c_1
        - pip 19.0.3 py37_0
        - python 3.7.3 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 40.8.0 py37_0
        - sqlite 3.27.2 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - absl-py >=0.4
        - grpcio >=1.6.3
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - markdown >=2.6.8
        - numpy >=1.12.0
        - protobuf >=3.6.0
        - python >=3.7,<3.8.0a0
        - six >=1.10.0
        - werkzeug >=0.11.15
test:
    commands:
        - tensorboard --help
    imports:
        - tensorboard
    requires:
        - tensorflow-base >=1.13.0,<1.14.0a0
        - tensorflow-estimator 1.13.0.*
about:
    dev_url: https://github.com/tensorflow/tensorboard
    home: http://tensorflow.org/
    license: Apache 2.0
    license_family: Apache
    summary: TensorBoard lets you watch Tensors Flow
extra:
    copy_test_source_files: true
    final: true
