Abdulkarim Shwani's Resume
=============================
# Ph.D. Candidate and Teaching Assistant Cell and Molecular Biology Program Biological Sciences Department University of Arkansas/ Fayetteville

# 601 Science Engineering Building 850 W. Dickson St., Fayetteville, AR 72701 aashwani@uark.edu (479) 301-9441

# EDUCATION
    BACHELOR OF SCIENCE, Biology Salahaddin University, June 2002 
    
    BACHELOR OF Arts, English Language Salahaddin University, June 2006 
    
    Master OF SCIENCE, Biology/ Parasitology Salahaddin University, June 2009 
    
    Ph.D. Candidate, Biology/ Cell and Molecular Biology University of Arkansas/ Fayetteville, August 2013 - Present

# RESEARCH INTERESTS 
	• Cell and Molecular Biology 
	• Parasitology 
	• Genomics and Bioinformatics

# GRANTS

Accepted --> NSF proposal 2014. Genetic and phylogenetic diversity of Entamoeba. J.D. Silberman and Abdulkarim Shwani. 
Accepted --> NSF proposal 2014. Genetic and phylogenetic diversity of Entamoeba. J.D. Silberman and Abdulkarim Shwani. 
Accepted --> NSF proposal 2015. Genetic and phylogenetic diversity of Entamoeba. J.D. Silberman and Abdulkarim Shwani. 
Accepted --> ABI proposal 2016. Phylogenomic comparison of Staphylococcus agnetis isolates from dairy cattle mammary glands and bacterial chondronecrosis with osteomyelitis in broilers. Douglas D. Rhoads and Abdulkarim Shwani. 
Accepted --> ABI proposal 2017. Direct Genome Evolution of a Staphylococcus agnetis isolate, 1379, from dairy cattle mammary glands, versus S. agnetis isolate, 908, from bacterial chondronecrosis with osteomyelitis in broilers. Douglas D. Rhoads and Abdulkarim Shwani. 
Accepted --> ABI proposal 2018. Directed Genome Evolution for Macrophage-killing in Staphylococcus agnetis an Agent of Bacterial Chondronecrosis with Osteomyelitis in Broilers. Douglas D. Rhoads and Abdulkarim Shwani. In Review ABI proposal 2019. Whole Genome Resequencing to Identify Genetic Determinants of Resistance to Bacterial Chondronecrosis with Osteomyelitis Leading to Lameness (Proposal). Douglas D. Rhoads, Adnan Alrubaye and Abdulkarim Shwani.
Accepted --> NSF proposal 2015. Genetic and phylogenetic diversity of Entamoeba. J.D. Silberman and Abdulkarim Shwani. 
Accepted --> ABI proposal 2016. Phylogenomic comparison of Staphylococcus agnetis isolates from dairy cattle mammary glands and bacterial chondronecrosis with osteomyelitis in broilers. Douglas D. Rhoads and Abdulkarim Shwani. Accepted ABI proposal 2017. Direct Genome Evolution of a Staphylococcus agnetis isolate, 1379, from dairy cattle mammary glands, versus S. agnetis isolate, 908, from bacterial chondronecrosis with osteomyelitis in broilers. Douglas D. Rhoads and Abdulkarim Shwani. Accepted ABI proposal 2018. Directed Genome Evolution for Macrophage-killing in Staphylococcus agnetis an Agent of Bacterial Chondronecrosis with Osteomyelitis in Broilers. Douglas D. Rhoads and Abdulkarim Shwani. In Review ABI proposal 2019. Whole Genome Resequencing to Identify Genetic Determinants of Resistance to Bacterial Chondronecrosis with Osteomyelitis Leading to Lameness (Proposal). Douglas D. Rhoads, Adnan Alrubaye and Abdulkarim Shwani.


# HONORS AND AWARDS
2009 --> Higher Committee for Educational Development in Iraq (HCED) Scholarship sponsored by Iraqi Government. 
2010 --> Human Capacity Development Program (HCDP) Scholarship sponsored by Kurdistan Regional Government (KRG). 
2020 --> Plant and Animal Genome conference travel award.
2020 --> Arkansas Bioinformatic Consortium (AI) poster competition second place award.


# REFEREED PUBLICATIONS 
1. Shwani, A. A. A., & Abdullah Sh. M. A. (2007). The inhabitant fishes in Darbanduikhan Lake In North of Iraq and Methods for development their culture. Egyptian journal of Aquatic Culture and Fishery - Ain Shames University. Vol (11), N (3), 2007. 
2. Shwani, A. A. A., Abdullah Sh. M. A. & Asmat G. (2010). Two New Species of Trichodina Ehrenberg, 1838 (Ciliophora: Trichodinidae) from Silurus triostegus in Iraq. Europ. J. Sc. Res. 40 (4): 598-604. http://www.europeanjournalofscientificresearch.com/issues/EJSR_134_3_02.pd2. 
3. Shwani, A. A. A., & Abdullah Sh. M. A. (2010). Ectoparasites of the Asian Catfish Silurus triostegus (Heckel, 1843) from Greater Zab River- Kurdistan Region- Iraq. Kurdistan 3rd Conference on Biological Sciences Duhok University. 
4. Abdullah, Sh. M. A. & Shwani A. A. A. (2010). Endoparasites of the Asian Catfish Silurus triostegus (Heckel, 1843) from Greater Zab River- Kurdistan Region- Iraq. Kurdistan 3rd Conference on Biological Sciences Duhok University.


# MANUSCRIPTS IN REVIEW 
1. Shwani, Abdulkarim, & Abdullah Sh. M. A. (2010). Treatment of Trichodiniasis using chemical a substance. (in review). 
2. Shwani, Abdulkarim, & Silberman J.D. (2014). The temperature and salinity barriers in which different isolates of Entamoeba moshkovskii can live. (In Review). 
3. Shwani, Abdulkarim, & Rhoads D. D. (2016). Phylogenomic comparison of Staphylococcus agnetis isolates from dairy cattle mammary glands and bacterial chondronecrosis with osteomyelitis in broilers. (In Review). 
4. Shwani, Abdulkarim, & Rhoads D.D. (2019). Directed Genome Evolution for Macrophage-killing in Staphylococcus agnetis an Agent of Bacterial Chondronecrosis with Osteomyelitis in Broilers. (In Review).


# MANUSCRIPTS IN PREPARATION 
1. Shwani, Abdulkarim, & Abdullah Sh. M. A. (2010). Endoparasites of softshell water turtle Rafetus sp. (in writing process). 
2. Shwani, Abdulkarim, & Abdullah Sh. M. A. (2010). New recorded Trichodina sp. of Silurus triostigus. (in writing process).


# ONGOING/CURRENT RESEARCH PROJECTS 
1. Shwani, Abdulkarim, & Rhoads D. D. (2018). Direct Genome Evolution of a Staphylococcus agnetis isolate, 1379, from dairy cattle mammary glands, versus S. agnetis isolate, 908, from bacterial chondronecrosis with osteomyelitis in broilers. (In writing). 
2. Shwani, Abdulkarim, & Rhoads D. D. (2019). Isolating peripheral blood mononuclear cells (PBMCs) from two lines of chicken; leghorn and Arkansas Random Breed (ARB); and expose them to Staphylococcus agnetis (908), to study the ability of macrophage survival between different lines of chicken. (In experimenting). 


# PLATFORM PRESENTATIONS 
1. Shwani, A. A. A., & Abdullah Sh. M. A. (2010). Ectoparasites of the Asian Catfish Silurus triostegus (Heckel, 1843) from Greater Zab River- Kurdistan Region- Iraq. Kurdistan 3rd Conference on Biological Sciences Duhok University. 
2. Abdullah, Sh. M. A. & Shwani A. A. A. (2010). Endoparasites of the Asian Catfish Silurus triostegus (Heckel, 1843) from Greater Zab River- Kurdistan Region- Iraq. Kurdistan 3rd Conference on Biological Sciences Duhok University. 


# POSTER PRESENTATIONS 
1. Shwani, Abulkarim. (2014). Development of an invertebrate host/parasite model system for a human infecting species of Entamoeba. At INBRE Fall 2014 Conference in University of Arkansas/ Fayetteville. 
2. Shwani, Abulkarim; Pamela Adkins; Michael Calcutt; John Middleton; and Douglas Rhoads. (2017). Phylogenomic comparison of Staphylococcus agnetis isolates from dairy cattle mammary glands and bacterial chondronecrosis with osteomyelitis in broilers. At PAG XXV conference in San Diego California in January 14-18, 2017. 
3. Shwani, Abulkarim; Sura Zaki; Sohita Ojha; and Douglas Rhoads. (2018). Directed Genome Evolution of a Staphylococcus agnetis isolate, 1379, from dairy cattle mammary glands, versus S. agnetis isolate 908, from bacterial chondronecrosis with osteomyelitis in broilers. At PAG XXVI conference in San Diego California in January 13-17, 2018. 
4. Shwani, Abulkarim; Nnamdi Ekesi; Sura Zaki; and Douglas Rhoads. (2019). Directed Genome Evolution for Macrophage-killing in Staphylococcus agnetis an Agent of Bacterial Chondronecrosis with Osteomyelitis in Broilers. At PAG XXVI conference in San Diego California in January 12-16, 2019. 
5. Shwani, Abulkarim; Sura Zaki; Sonali Lenaduwe, Sohita Ojha and Douglas Rhoads. (2020). Directed Genome Evolution Identifies Deoxyribose Phosphate Aldolase as a Macrophage Survival Factor in Staphylococcus agnetis. At PAG XXVIII conference in San Diego California in January 11-15, 2019. 


# UNDERGRADUTES SUPERVISED 
1. Samir Gardi, (2012). The survey of ectoparasites and endoparasites infecting Mylopharyngodon piceus fish. 
2. Hamad Salih, (2012). The survey of ectoparasites and endoparasites infecting Cyprinus carpio fish. 



# PROFESSIONAL SERVICE Falcon group Company - A Private Security Company working with USA Troops. The company used to provide guards for the convoys delivered to USA Army all over Iraq/ EERBIL/ KURDISTAN REGION/ IRAQ Receptionist/ Translator June 2007 to June 2008
	• Receptionist, was responsible for the main gate of the camp of the company/ Security Division, and controlled the entrance of visitors. 
	• Phone operator, was responsible for operating contact phones and directing to the callers inside and outside the camp. 
	• Translator, worked as translator inside the camp between the American workers and the local people who all worked together in the camp. 


# Down Town Erbil Company – A Private Building Company worked in Building the major Bazar (Market) in the entire Middle East, called Nishtiman Bazar, in Erbil City / ERBIL/ KURDISTAN REGION/ IRAQ Camp Manager July 2008 to July 2012 
	• Was the administrator of workers camp and supervised the workers who used to work in building the new bazar in Erbil 
	• Providing the workers their life items such as rooms, beds, water, electricity and etc. 
	• Cooperating the Security Division in the Company and sharing information about any new worker who contacted our company. 
	• I have to leave the job because I got accepted from HCDP/ KRG scholarship by 2012 and I had to travel to the US for my PhD study in CEMB. 


# TEACHING EXPERIENCEs:
	# At SALAHADDIN UNIVRSITY/ ERBIL/ KURDISTAN REGION/ IRAQ Biology Assistant March 2004 to April 2006 
		• Worked in the teaching biology laboratories of the department. 
		• Assisting teachers in practice lessons doing experiments, using microscopes and slides and lab experiments for students. 
		• Worked in the purchasing office of the college for a year. 
	
	# SALAHADDIN UNIVRSITY/ ERBIL/ KURDISTAN REGION/ IRAQ Assistant Lecturer March 2009 to April 2012 
		• After I finished my M.Sc. study, I have been teaching the senior of Biology department the practical Parasitology up to 1/7/2012, by the time I got my Ph.D. scholarship. 
		• Taught English language to freshmen of Biology department.
		
	# UNIVRSITY of RKANSAS/ FAYETTEVILLE/ ARKANSAS/ USA Teaching Assistant January 2016 to Present 
		• Teaching Principle of Biology Lab to undergrads of University of Arkansas starting from January 2016 up to June 2016. 
		• Teaching General Microbiology Lab to undergrads of University of Arkansas starting from August 2016 and 2019. 
		• Teaching General Microbiology Lab to undergrads of University of Arkansas starting from August 2019 and ongoing.
	# UNIVRSITY of RKANSAS/ FAYETTEVILLE/ UNIVRSITY of RKANSAS FARM 
		• Assisting my fellow researchers while doing some experimental infections of chicken with 6 bacterial isolates are Staphylococcus agnetis 908 (our type strain from chicken bacterial chondronecrosis with osteomyelitis (BCO)), S. agnetis 1379 (from cattle), S. hyicus (from chicken BCO, our farm), S. hyicus (from chicken BCO, from commercial farm), and two isolates of E. coli (from chicken BCO, two different commercial farms owned by OK Foods) on Dec 5, 2016-Jan 29, 2017, for 56 days. 


# SKILLS 
	• Teaching and experimenting Biological sciences. 
	• Teaching English Language. 	
	• Bioinformatics and programming. 
	• Microbiology Lab works. 
	• Accounting: keeping financial accounts according to the company model, check the accountancy financial affairs, and invoices, arranging the data and other related duties to maximize the benefits of the company. 
	• Administration: Answering phones, arranging meetings and scheduling appointments, maintaining files and databases and handling correspondence, bookkeeping duties, such as sending out invoices and balancing account spreadsheets. 
	• Computer programs and internet: Familiar with necessary office programs and necessary online programs, such the programs used for Bioinformatics. 
	• Languages: English, Kurdish, Arabic. Translate writing and speeches for school children from English to any of the other two languages and vice versa. 




# REFERENCE 

	• Dr. Rhoads, D. D. The Professor of Cell and Molecular Biology (CEMB) and The director of CEMB Program/ University of Arkansas/ Fayetteville. drhoads@uark.edu 
	
	• Dr. Kwon, Young Min. Microbiologist; a professor in CEMB, Dale Bumpers College of Agricultural, Food & Life Sciences (POSC)-Poultry Science/ University of Arkansas/ Fayetteville. ykwon@uark.edu 
	
	• Dr. Abdullah, Sh. M. A., The Professor of Parasitology, Science Education College/ Biology Department/ Salahaddin University/ Erbil/ Iraq. shamall_m_a_abdullah@yahoo.com Dr. Ali, W. Kh., The Professor of Entomology, Science Education College/ Biology Department/ Salahaddin University/ Erbil/ Iraq. Wand.Ali@su.edu.krd

