# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/absl-py-0.8.1-python_3.7-on-linux_64, last modified Fri Nov  8 14:50:45 2019
# ------------------------------------------------

package:
    name: absl-py
    version: 0.8.1
source:
    fn: absl-py-0.8.1.tar.gz
    sha256: d9129186431e150d7fe455f1cb1ecbb92bb5dba9da9bc3ef7b012d98c4db2526
    url: https://pypi.io/packages/source/a/absl-py/absl-py-0.8.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py37_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.7.5 h0371630_0
        - readline 7.0 h7b6447c_5
        - setuptools 41.6.0 py37_0
        - six 1.12.0 py37_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    run:
        - python >=3.7,<3.8.0a0
        - six
test:
    imports:
        - absl
        - absl.flags
        - absl.logging
        - absl.testing
about:
    dev_url: https://github.com/abseil/abseil-py
    doc_url: https://abseil.io/docs/
    home: https://abseil.io/
    license: Apache 2.0
    license_family: Apache
    license_file: /tmp/build/80754af9/rsync-recipes/absl-py-0.8.1-python_3.7-on-linux_64/LICENSE
    summary: Abseil Python Common Libraries, see https://github.com/abseil/abseil-py.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jjhelmus
