# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/tbb-2020.0-on-linux_64, last modified Tue Feb  4 20:26:51 2020
# ------------------------------------------------

package:
    name: tbb
    version: '2020.0'
source:
    fn: tbb2020_oss_src.tgz
    sha256: db80f4f7abb95c2d08fe64abdc0a9250903e4c725f1c667ac517450de426023a
    url: https://github.com/intel/tbb/archive/2020.tar.gz
build:
    number: '0'
    script: python build/build.py --build-args="stdver=c++11 runtime=conda" --install-libs
    string: hfd86e86_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - ca-certificates 2020.1.1 0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 he6710b0_1
        - openssl 1.1.1d h7b6447c_3
        - python 3.8.1 h0371630_1
        - readline 7.0 h7b6447c_5
        - sqlite 3.31.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - python -c "import ctypes; assert 11100 == ctypes.cdll[r'libtbb.so.2']       ['TBB_runtime_interface_version']()"
    requires:
        - python *
about:
    dev_url: https://github.com/01org/tbb
    doc_url: https://software.intel.com/en-us/node/506039
    home: http://www.threadingbuildingblocks.org
    license: Apache 2.0
    license_file: LICENSE
    summary: High level abstract threading library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - anton-malakhov
        - jschueller
